### ISSUE TITLE
Комментарии

### ISSUE THREAD

**Issue by ubcent** [lionesy/js#1]
Добрый день.
1. [L9 1.html](https://github.com/lionesy/js/blob/master/jquery/1.html#L9) и [L9 2.html](https://github.com/lionesy/js/blob/master/jquery/2.html#L9) Попробуйте сделать с помощью цикла [$.each](http://api.jquery.com/jquery.each/)
2. [L9](https://github.com/lionesy/js/blob/master/jquery/3.html#L9) selected это не атрибут, а свойство. Об отличиях почитать можно [здесь](http://api.jquery.com/prop/). Соответственно и метод лучше использовать другой.

**Comment by lionesy** [comment]
Спасибо! Не до конца еще разобралась с github :)
