### ISSUE TITLE
serialize

### ISSUE THREAD

**Issue by ubcent** [lionesy/js#2]
[L12](https://github.com/lionesy/js/blob/master/validator/index.html#L12) сделайте какую-нибудь закраску при успешном/не успешном выполнении валидации. 

[L16](https://github.com/lionesy/js/blob/master/validator/index.html#L16) почему отправляется только нажатый radio? Мне кажется фильтр **:checked** здесь не нужен

**Дополнительное задание**: попробуйте для сбора данных с формы воспользоваться методами [serialize](https://api.jquery.com/serialize/) и [serializeArray](https://api.jquery.com/serializeArray/)

**Comment by lionesy** [comment]
Исправила

**Comment by ubcent** [comment]
[L13](https://github.com/lionesy/js/blob/master/validator/index.html#L13) вот здесь необязательно обрамлять объект в {}, соответственно и дополнительная переменная тоже не нужна.
